name: Mention team for label
on:
  discussion:
    types: [labeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  mention:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Comment in discussion
        uses: shield-wall/comments@main
        if: github.event.label.name == 'bug'
        with:
          organization: ${{ github.event.organization.login }}
          repository: ${{ github.event.repository.name }}
          discussionId: ${{github.event.discussion.number }}
          body: |
            This is a multi-line test comment for the 'Bug' label
            - With GitHub **Markdown** :sparkles:
            - This is relevant for you @MocktoverseFour/github-emea
